# Generated by Django 3.2.18 on 2023-04-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20230422_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
