# Generated by Django 3.2.18 on 2023-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My grocery list', max_length=100)),
                ('item', models.CharField(max_length=100)),
            ],
        ),
    ]
