# Generated by Django 3.2.18 on 2023-04-24 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_list', '0003_delete_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My grocery list', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
